### ISSUE TITLE
Step 3. 정산 기능 개발

### ISSUE THREAD

**Issue by cchoijjinyoung** [dojindo/minipay-jinyoung#4]
## Description
정산 기능을 개발합니다. 1/N 정산과, 랜덤 정산을 구현합니다.

## To-do
- [x] 1/N 정산 금액 분배 API 개발
- [x] 랜덤 정산 금액 분배 API 개발
- [x] 정산 요청 API 개발
