### ISSUE TITLE
Step 4. 송금 기능 구조 변경

### ISSUE THREAD

**Issue by cchoijjinyoung** [dojindo/minipay-jinyoung#6]
## Description
송금 API의 구조를 변경합니다. 이제는 송금 사용자의 설정에 따라 바로 송금이 이루어지지 않을 수 있습니다.
- [즉시 송금 / Pending 송금]으로 나뉘어집니다.
- 즉시 송금은 이전 구조와 마찬가지로 송신계좌의 출금과 수신계좌의 입금이 동시에 이루어집니다.
- Pending 송금은 송신계좌의 출금은 바로 이루어지지만, 수신계좌의 입금은 수신자가 송금을 확인하고 금액을 받길 원할 때 이루어집니다.
- 72시간이 지나면 자동 취소되고, 24시간이 남았을 때는 remind 알림이 발송되어야합니다.

## To-do
- [x] 회원 설정 테이블 추가
- [x] Pending 내역 테이블 추가
- [x] 송금 구조 변경
- [ ] Pending 금액 받기 API 추가
- [ ] Pending 금액 거절 API 추가
- [ ] Pending 송금 취소 API 추가
- [ ] 리마인드 알림 Batch 처리(알림: FCM 사용)
  - [x] FCM 프로젝트와 연결
  - [x] FCM 토큰 저장 요청
  - [x] FCM Token 전송 테스트
  - [ ] 스케줄러 설정 : 매일 9시 알림 대상자 취합
